const BOOKING_URL="https://calendly.com/v-atul1910/30min";
function openBooking(){window.open(BOOKING_URL,'_blank')}
const nav=document.getElementById('nav'),tog=document.getElementById('tog'),links=document.getElementById('links');
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>50));
tog?.addEventListener('click',e=>{e.stopPropagation();tog.classList.toggle('open');links.classList.toggle('open');document.body.style.overflow=links.classList.contains('open')?'hidden':''});
document.addEventListener('click',e=>{if(links.classList.contains('open')&&!links.contains(e.target)&&!tog.contains(e.target)){tog.classList.remove('open');links.classList.remove('open');document.body.style.overflow=''}});
links?.querySelectorAll('a').forEach(l=>l.addEventListener('click',()=>{tog.classList.remove('open');links.classList.remove('open');document.body.style.overflow=''}));
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',function(e){const h=this.getAttribute('href');if(h==='#')return;const t=document.querySelector(h);if(t){e.preventDefault();window.scrollTo({top:t.getBoundingClientRect().top+window.scrollY-nav.offsetHeight-20,behavior:'smooth'})}})});
const rm=window.matchMedia('(prefers-reduced-motion:reduce)').matches;
document.addEventListener('DOMContentLoaded',()=>{
  if(!rm)initHero();
  if(!rm){const co=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const el=e.target,tgt=parseInt(el.dataset.target),dur=900,st=performance.now();function tk(n){const p=Math.min((n-st)/dur,1),v=1-Math.pow(1-p,3);el.textContent=Math.round(v*tgt).toLocaleString();if(p<1)requestAnimationFrame(tk);else el.classList.add('counted')}requestAnimationFrame(tk);co.unobserve(el)}})},{threshold:.5});document.querySelectorAll('[data-target]').forEach(el=>co.observe(el))}else{document.querySelectorAll('[data-target]').forEach(el=>el.textContent=parseInt(el.dataset.target).toLocaleString())}
});
function initHero(){const ss=document.querySelectorAll('.wf-s'),st=document.getElementById('wfSt');if(!ss.length)return;function run(){ss.forEach(s=>s.classList.remove('vis'));if(st){st.textContent='';st.className='wf-stat'}ss.forEach((s,i)=>{setTimeout(()=>{s.classList.add('vis');if(st){const tx=['New lead...','Responding...','Qualifying...','Following up...','Booking...','Ready for agent'];const cl=['wf-stat','wf-stat','wf-stat','wf-stat','wf-stat','wf-stat ready'];st.textContent=tx[i]||'';st.className=cl[i]||'wf-stat'}},i*1200)});setTimeout(run,ss.length*1200+3500)}const ho=new IntersectionObserver(es=>{if(es[0].isIntersecting){run();ho.unobserve(es[0].target)}},{threshold:.2});ho.observe(document.getElementById('heroWf'))}